const express = require("express")
const app = express()
const cors = require("cors")
const router = require('./modules')
const bodyParser = require('body-parser')
const path = require('path')

app.use(cors())
app.use(express.json())
const { PORT } = require("./config")
app.use(router)

app.use(bodyParser.urlencoded({ extended: true }))
app.use('/public', express.static(path.resolve(__dirname, './public')))
app.listen(9000,console.log('create server!'))
