const express = require("express")
const app = express()
const cors = require("cors")
const router = require('./modules')
const bodyParser = require('body-parser')
const { PORT } = require("./config")
app.use(cors())
app.use(express.json())
app.use(router)
app.use(bodyParser.urlencoded({ extended: true }))
app.use('/public', express.static('/public'))
app.listen(PORT,console.log('create server!'))
